### ISSUE TITLE
⚡ Newcastle | Level 3 | Fit off power

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/SSW.Automation#1]
## Description
The south side of the office requires power to be fitted off.

## Work items
- [ ] #3
- [ ] Terminate on switchboard
- [ ] Test and Tag the outlets

## Acceptance Criteria

- [ ] Power works
- [ ] Checked by Adam
